spring:
  datasource:
    url: jdbc:mysql://demomysql:3306/demo
    username: root
    password: root
    platform: mysql
    initialize: true
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://demomysql:3306/demo
    username: root
    password: root
    initialize: true
